server {

    listen 80;
    server_name _;

    # ==========================
    # FastAPI routes
    # ==========================

    location /docs {
        proxy_pass http://127.0.0.1:8000/docs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /openapi.json {
        proxy_pass http://127.0.0.1:8000/openapi.json;
        proxy_set_header Host $host;
    }

    location /uploads/ {
        proxy_pass http://127.0.0.1:8000/uploads/;
        proxy_set_header Host $host;
    }

    location /tickets {
        proxy_pass http://127.0.0.1:8000/tickets;
        proxy_set_header Host $host;
    }

    location /emails {
        proxy_pass http://127.0.0.1:8000/emails;
        proxy_set_header Host $host;
    }

    # ==========================
    # Next.js
    # ==========================

    location / {

        proxy_pass http://127.0.0.1:3000;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;

        proxy_cache_bypass $http_upgrade;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;

    }

}